server:
  port: 8081

spring:
  application:
    name: oauth2

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.authorization: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.web.cors: DEBUG
    com.amalitech.healthhub.auth: DEBUG

oauth2:
  auth-callback-url: http://localhost:4200/auth/callback
  post-logout-redirect-url: http://localhost:4200/logout



app:
  base-url: http://localhost:8081
